resources:
  - name: trading-app
    type: git
    source: {
      uri: "https://github.com/liquidMocha/trading-app.git",
      username: ((username)),
      password: ((password))
    }

jobs:
  - name: build
    plan:
      - get: trading-app
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8
          inputs:
           - name: trading-app
          run:
            path: ./trading-app/pipeline/build.sh
